### ISSUE TITLE
set ceaser cipher key

### ISSUE THREAD

**Issue by ihurrahi** [iamsammak/thehuntgame#199]
after chris finds out how many tables there are

**Comment by cschois1** [comment]
Is it possible to temporarily set this to 30 for play testing? The reception diagram I will provide has 30 guest tables, so our test players would be able to solve the puzzle the right way in that case. I will still update you guys once the table count is finalized.

**Comment by pewpewpowpow** [comment]
@cschois1 is the number of tables set at 30 still or do we need to change it?

**Comment by cschois1** [comment]
Sorry, we still haven't figured this out! Will let you know ASAP!

**Comment by cschois1** [comment]
Ok guest tables = 31. Let's use that as the cipher key. Also, just to prevent a little brute forcing, can we change the way the letters are displayed such that they are circular instead of linear? That would make it harder for people to brute force it, but still easy enough to solve once you have the cipher key.

**Comment by cschois1** [comment]
If we can have the letters displayed in a circular pattern, let's make sure the first letter is not at the very top or the left-most one, so that brute forcers don't get it right by chance.

**Comment by ihurrahi** [comment]
@cschois1, just to be clear, the highest table number is 31, and there _will_ be a table 26?

**Comment by ihurrahi** [comment]
yea, we can do the circular thing, but im not convinced it will deter brute forcers? they can still go through all 26 possibilities
![Screenshot from 2019-04-19 22-17-17](https://user-images.githubusercontent.com/614205/56453100-5f7a4600-62f1-11e9-9d96-d0c68564e602.png)

**Comment by cschois1** [comment]
Yeah, the highest guest table number is 31 and we will have a table 26. It shouldn't matter since the cipher key will be the same for everyone regardless of their table number. We'll just make sure to place people who aren't likely to play at the key tables (i.e. tables 5 and 21).

And yeah the circle can't stop even the brutest of forcers (i.e. Sheldon), but it would make it more difficult for them. If they used an online tool like https://www.dcode.fr/caesar-cipher , then they'd have to randomly guess where the word starts. It's true that they can still get somewhere with brute forcing with the online tool, but at least it's a little harder and goes one step closer to leveling the playing field between the brute forcers/lucky guessers and the true puzzle solvers.

Let me know what you think and if I'm missing something!
