### ISSUE TITLE
puzzle 7 updates

### ISSUE THREAD

**Issue by ihurrahi** [iamsammak/thehuntgame#219]
make it slightly easier by removing some of the looping logic clues

**Comment by cschois1** [comment]
Ok let's try this new set of clues. Nothing connects more than once from one person to another, so it should be a lot more straightforward. I also removed the clue that said "ignore" a clue, since I know that can make people second-guess what the clue should be saying instead. Let's see how this turns out for the next playtesters.

I have highlighted in the document all the clues that I have changed. The actual answer key has not changed.

[Puzzle 7 Key Update 03282019.docx](https://github.com/iamsammak/thehuntgame/files/3020572/Puzzle.7.Key.Update.03282019.docx)
